// Angular/innoteq-angular-frontend/src/app/new-sale/new-sale.component.ts
import { Component, OnInit } from '@angular/core';
import { NewSaleService } from '../service/new-sale.service';
import {ngDebug} from "@angular/cli/src/utilities/environment-options";

@Component({
  selector: 'app-new-sale',
  templateUrl: './new-sale.component.html',
  styleUrls: ['./new-sale.component.css'],
})
export class NewSaleComponent implements OnInit {
  personName: string = '';
  inputs: { quantity: number | null; productName: string | null }[] = [{ quantity: null, productName: null }];
  productOptions: string[] = ['szar', 'fos'];

  constructor(private newSaleService: NewSaleService) {}

  ngOnInit() {
    this.fetchProductOptions();
    this.addInput();
  }

  submitForm() {
    console.log("submit megíhvva")
    const personItemData = {
      personModel: {
        personName: this.personName
      },
      itemModels: this.inputs.map(input => ({
        productName: input.productName,
        quantity: input.quantity
      }))
    };

    this.newSaleService.saveNewSale(personItemData).subscribe(
      response => {
        console.log(response);
        alert('Mentve az adatbázisba!');
      },
      error => {
        console.error(error);
      }
    );
  }

  addInput() {
    console.log("addInput meghívva")
    this.inputs.push({ quantity: null, productName: null });
  }

  removeInput(index: number) {
    console.log("removeInput meghívva")
    this.inputs.splice(index, 1);
  }

  fetchProductOptions() {
    this.newSaleService.getProductOptions().subscribe(
      (response: any[]) => {
        this.productOptions = response.map((product: any) => product.productName);
      },
      error => {
        console.error(error);
      }
    );
  }

  public fun(){
    console.log("fun")
  }

}

<form (ngSubmit)="submitForm()">
  <h4><p style="color:white;">Új vásárlás rögzítése</p></h4>
  <p>
    Ugyanazzal a névvel többször leadott rendelés esetén az illetőhöz más-más ID fog tartozni,
    <br/>de a dolgozói fogyasztásriportban egy név csak egyszer szerepel.
  </p>
  <input type="text" [(ngModel)]="personName" name="personName" placeholder="Dolgozó neve" required>
  <div *ngFor="let input of inputs; let index = index">
    <select [(ngModel)]="input.productName" name="productName" required>
      <option *ngFor="let option of productOptions" [value]="option">{{ option }}</option>
    </select>
    <input type="number" [(ngModel)]="input.quantity" name="quantity" placeholder="Mennyiség" required>
    <button type="button" (click)="removeInput(index)">Törlés</button>
  </div>
  <p>
    <button type="button" (click)="addInput()">Hozzáadás</button>
  </p>
  <button type="submit">Értékesítés leadása</button>
</form>

<button (click)="fun()">xy</button>

// React/react_beadando/src/components/NewSale.tsx
// NewSale.tsx
import React, {useState, useEffect} from 'react';
import axios from 'axios';
import './NewSale.css';

const NewSale: React.FC = () => {
    const [personName, setPersonName] = useState('');
    const [inputs, setInputs] = useState([{productName: '', quantity: ''}]);
    const [selectedProducts, setSelectedProducts] = useState<{ [key: number]: boolean }>({});
    const [productOptions, setProductOptions] = useState<string[]>(['Termék A', 'Termék B', 'Termék C']);

    const handleDropdownClick = (index: number) => {
        setSelectedProducts((prevSelectedProducts) => ({
            ...prevSelectedProducts,
            [index]: !prevSelectedProducts[index]
        }));
    };

    const handleOptionClick = (option: string, index: number) => {
        setInputs((prevInputs) =>
            prevInputs.map((input, i) =>
                i === index ? {...input, productName: option} : input
            )
        );
        setSelectedProducts((prevSelectedProducts) => ({
            ...prevSelectedProducts,
            [index]: false
        }));
    };

    const addInput = () => {
        setInputs([...inputs, {productName: '', quantity: ''}]);
    };

    const removeInput = (index: number) => {
        setInputs(inputs.filter((_input, i) => i !== index));
    };


    const submitForm = () => {
        const personItemData = {
            personModel: {
                personName: personName,
            },
            itemModels: inputs.map((input) => ({
                productName: input.productName,
                quantity: input.quantity,
            })),
        };

        axios
            .post('/save-new-sale', personItemData, {
                baseURL: 'http://localhost:8080',
            })
            .then((response) => {
                console.log(response.data);
                alert('Mentve az adatbázisba!');
            })
            .catch((error) => {
                console.error(error);
            });
    };

    const fetchProductOptions = () => {
        axios
            .get('/productInfo', {
                baseURL: 'http://localhost:8080',
            })
            .then((response) => {
                if (response.data && Array.isArray(response.data)) {
                    setProductOptions(response.data.map((product: { productName: string }) => product.productName));
                } else {
                    console.error('Nem sikerült lekérni a termékinformációkat.');
                }
            })
            .catch((error) => {
                console.error('Hiba történt a termékinformációk lekérése közben:', error);
            });
    };

    useEffect(() => {
        fetchProductOptions();
        addInput(); // Alapból egy mezőt hozzáadunk
    }, []);

    return (
        <div className="container">
            <div className="columns">
                {/*<div className="column is-half">*/}
                <form onSubmit={submitForm} className="box">
                    <h4 className="title has-text-white">Új vásárlás rögzítése</h4>
                    <p>
                        Ugyanazzal a névvel többször leadott rendelés esetén az illetőhöz más-más ID fog
                        tartozni, <br/>
                        de a dolgozói fogyasztásriportban egy név csak egyszer szerepel.
                    </p>
                    <br/>
                    <input
                        className="input"
                        type="text"
                        value={personName}
                        onChange={(e) => setPersonName(e.target.value)}
                        placeholder="Dolgozó neve"
                        required
                    />
                    {inputs.map((input, index) => (
                        <div key={index} className="field">
                            <div className="field">
                                {/*<label className="label">Termék kiválasztása</label>*/}
                                <div
                                    className={`dropdown ${selectedProducts[index] ? 'is-active' : ''}`}
                                    onClick={() => handleDropdownClick(index)}
                                >
                                    <div className="dropdown-trigger">
                                        <button className="button" aria-haspopup="true"
                                                aria-controls="dropdown-menu">
                                            <span>{input.productName || 'Válasszon terméket!'}</span>
                                            <span className="icon is-small">
                                                    <i className="fas fa-angle-down" aria-hidden="true"></i>
                                                </span>
                                        </button>
                                    </div>
                                    <div className="dropdown-menu" id="dropdown-menu" role="menu">
                                        <div className="dropdown-content">
                                            {productOptions.map((option, optionIndex) => (
                                                <a key={optionIndex} className="dropdown-item"
                                                   onClick={() => handleOptionClick(option, index)}>
                                                    {option}
                                                </a>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="control">
                                <input
                                    className="input"
                                    type="number"
                                    value={input.quantity || ''}
                                    onChange={(e) =>
                                        setInputs((prevInputs) =>
                                            prevInputs.map((prevInput, prevIndex) =>
                                                prevIndex === index ? {
                                                    ...prevInput,
                                                    quantity: e.target.value === '' ? '' : String(parseInt(e.target.value))
                                                } : prevInput
                                            )
                                        )
                                    }
                                    placeholder="Mennyiség"
                                    required
                                />
                            </div>
                            <div className="control">
                                <button className="button is-danger" type="button"
                                        onClick={() => removeInput(index)}>
                                    Törlés
                                </button>
                            </div>
                        </div>
                    ))}
                    <div className="mainField">
                        <div className="control">
                            <button className="button" type="button" onClick={addInput}>
                                Hozzáadás
                            </button>
                        </div>
                        <div className="control">
                            <button className="button is-primary" type="submit">
                                Értékesítés leadása
                            </button>
                        </div>
                    </div>
                </form>
                {/*</div>*/}
            </div>
        </div>
    );
};

export default NewSale;
