// React_v2/react_beadando/src/components/ListAllClosedSales.tsx
import React from 'react';
import { useQuery } from 'react-query';
import {getBaseURL} from "../BacendConfig.ts";

interface Item {
    [index: number]: any;
}

const fetchItemsWithPersonAndSaleData = async () => {
    const response = await fetch(getBaseURL()+'closed-sale-table', {
        method: 'GET'
    });
    const data = await response.json();
    return data.items;
};

const ListAllClosedSales: React.FC = () => {
    const { data: items = [], isError, isLoading } = useQuery<Item[]>(
        'closedSales',
        fetchItemsWithPersonAndSaleData
    );

    if (isLoading) return <div>Loading...</div>;
    if (isError) return <div>Error fetching data</div>;

    return (
        <center>
            <div>
                <br />
                <h4>Lezárt értékesítések</h4>
                <p>A lezárás pontos ideje szerint rendezve (legrégebben lezártak alul).</p>
                <table className="table">
                    <thead>
                    <tr>
                        <th>
                            <center>Dolgozó neve</center>
                        </th>
                        <th>
                            <center>Terméknév</center>
                        </th>
                        <th>
                            <center>Mennyiség</center>
                        </th>
                        <th>
                            <center>Végösszeg</center>
                        </th>
                        <th>
                            <center>Vásárlás pontos ideje</center>
                        </th>
                        <th>
                            <center>Lezárás pontos ideje</center>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {items.map((item, index) => (
                        <tr key={index}>
                            <td>
                                <center>{item[1]}</center>
                            </td>
                            <td>
                                <center>{item[2]}</center>
                            </td>
                            <td>
                                <center>{item[3]}</center>
                            </td>
                            <td>
                                <center>{item[4]}</center>
                            </td>
                            <td>
                                <center>{item[5]}</center>
                            </td>
                            <td>
                                <center>{item[6]}</center>
                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        </center>
    );
};

export default ListAllClosedSales;

// Angular/innoteq-angular-frontend/src/app/list-all-closed-sales/list-all-closed-sales.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';

@Component({
  selector: 'app-list-all-closed-sales',
  template: `

      <div>
        <br />
        <h4>Lezárt értékesítések</h4>
        <p>A lezárás pontos ideje szerint rendezve (legrégebben lezártak alul).</p>
        <table class="table">
          <thead>
            <tr>
              <th>Dolgozó neve</th>
              <th>Terméknév</th>
              <th>Mennyiség</th>
              <th>Végösszeg</th>
              <th>Vásárlás pontos ideje</th>
              <th>Lezárás pontos ideje</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let item of items; let i = index">
              <td>{{ item[1] }}</td>
              <td>{{ item[2] }}</td>
              <td>{{ item[3] }}</td>
              <td>{{ item[4] }}</td>
              <td>{{ item[5] }}</td>
              <td>{{ item[6] }}</td>
            </tr>
          </tbody>
        </table>
      </div>

  `,
  styles: [
    `
      .table {
        border-collapse: collapse;
        width: 100%;
        border: 1px solid #ddd;
      }

      .table td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }

      .table th {
        background-color: #f2f2f2;
      }

      div {
        background-color: red;
      }
    `,
  ],
})
export class ListAllClosedSalesComponent implements OnInit {
  items: any[] = [];

  ngOnInit() {
    this.fetchItemsWithPersonAndSaleData();
  }

  fetchItemsWithPersonAndSaleData() {
    axios
      .get('/closed-sale-table')
      .then((response) => {
        this.items = response.data.items;
      })
      .catch((error) => {
        console.error(error);
      });
  }
}
